server:
  port: 3000
logging:
  level:
    com:
      auth0:
        example: INFO
    org:
      springframework:
        # web: DEBUG
        web: INFO
        # security: DEBUG
        security: INO
        # boot: DEBUG
        boot: INFO
spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
  data:
    rest:
      basePath: /api
